# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33ca09f88a73da8bf3ba56203d2d3eaa67dd850c98f314ffa9d9596503d1fe7f7211e9144950164093b35fe412e7f673b583a5d776c16cdf2f7486e5d5bdf0a3

test:
  secret_key_base: 6383af18e2d6000f323827b4ea0347e6edcc02263242d89b4d99c091e1ce6a112dffa9fa2142270257643606044659ccdad8dd5421ca1581e71286639b343a51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
